const idea = "build me a clean personal portfolio";
const cards = [
  "Capture intake details for the target workflow.",
  "Generate a prioritized MVP action plan.",
  "Expose demo data through a small FastAPI surface."
];
const planSteps = [
  "Create a minimal API entrypoint.",
  "Add a deterministic agent core that mirrors the scoped MVP.",
  "Document architecture, build evidence, and demo flow.",
  "Commit generated files through the GitHub Agent."
];

export default function App() {
  return (
    <main className="shell">
      <section className="hero">
        <div>
          <p className="eyebrow">Generated MVP</p>
          <h1>Personal Portfolio</h1>
          <p className="lede">{idea}</p>
        </div>
        <div className="statusPanel" aria-label="MVP status">
          <span className="statusDot" />
          <strong>Me Clean Personal workflow ready</strong>
          <small>Frontend, backend, tests, docs, and database schema generated by MVPilot.</small>
        </div>
      </section>

      <section className="grid" aria-label="Core MVP features">
        {cards.map((card, index) => (
          <article className="card" key={card}>
            <span>{String(index + 1).padStart(2, '0')}</span>
            <p>{card}</p>
          </article>
        ))}
      </section>

      <section className="plan">
        <h2>Implementation Plan</h2>
        <ol>
          {planSteps.map((step) => <li key={step}>{step}</li>)}
        </ol>
      </section>
    </main>
  );
}